---
title: "Support Vector Machine"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# basic package
library(ggplot2)
library(dplyr)
library(readr)

#setwd
knitr::opts_knit$set(root.dir = "H:/Machine Learning/Day9")
```

```{r}
library(e1071)
set.seed(10111)
x = matrix(rnorm(40), 20 ,2)
y = rep(c(-1, 1), c(10, 10))
x[y == 1, ] = x[y == 1, ] + 1
toy <- data.frame(x, y =factor(y))
svm.fit <- svm(y ~ .,
               data = toy,
               kernel = "linear",
               cost = 10,
               scale = FALSE)
summary(svm.fit)
plot(svm.fit, toy, grid = 100)
```

```{r}
set.seed(1)
x <- matrix(rnorm(200 * 2), ncol = 2)
x[1:100, ] <- x[1:100, ] + 2
x[101:150, ] <- x[101:150, ] -2
y <- c(rep(1, 150), rep(2, 50))
toy2 <- data.frame(x = x, y = factor(y))
ggplot(data = toy2, aes(x = x.1, y = x.2, color = y)) +
    geom_point()
svm2 <- svm(y ~ ., data = toy2, kernel = 'radial',
            gamma = 2, cost = 1, scale = FALSE)
plot(svm2, toy2)
summary(svm2)

```

```{r}
library(rpart)
library(mlbench)
library(MASS)
library(dplyr)
```

```{r}
data(Pima.tr)
data(Pima.te)
str(Pima.tr)
```

```{r}
library(caret)
head(Pima.tr)
set.seed(1)
linear.tune <- tune.svm(type ~ ., data = Pima.tr,
                        kernel = "linear",
                        cost = c(0.001, 0.01, 0.1, 1, 3, 5))
summary(linear.tune)
linear.tune$best.model
```

```{r}
linear.test <- predict(linear.tune$best.model, Pima.te)
confusionMatrix(linear.test, Pima.te$type)
```

```{r}
poly.tune <- tune.svm(type ~ ., data = Pima.tr,
                      kernel = "polynomial",
                      degree = 2:5,
                      coef0 = c(0.1, 0.5, 1, 2, 3),
                      cost = c(0.001, 0.01, 0.1, 1, 3, 5)) #Grid Searching
summary(poly.tune)
```

```{r}
poly.test <- predict(poly.tune$best.model, Pima.te)
confusionMatrix(poly.test, Pima.te$type)
```

```{r}
radial.tune <- tune.svm(type ~ .,
                        data = Pima.tr,
                        kernel = "radial",
                        cost = c(0.001, 0.01, 0.1, 1, 3, 5))
summary(radial.tune)
```

```{r}
radial.test <- predict(radial.tune$best.model, Pima.te)
confusionMatrix(radial.test, Pima.te$type)
```

```{r}
sig.tune <- tune.svm(type ~ ., data = Pima.tr,
                     kernel = 'sigmoid',
                     coef0 = c(0.1, 0.5, 1, 2, 3),
                     cost = c(0.001, 0.01, 0.1, 1, 3, 5))
summary(sig.tune)
```

```{r}
sig.test <- predict(sig.tune$best.model, Pima.te)
confusionMatrix(sig.test, Pima.te$type)
```
